steps:
#Java build
- name: 'gcr.io/cloud-builders/mvn'
  args: ['package']
#Docker build
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=asia-northeast1-docker.pkg.dev/$PROJECT_ID/app/gke-javaee:$TAG_NAME', '.']
#Docker push
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/app/gke-javaee:$TAG_NAME']
#Deploy GKE
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - run
  - --filename=kubernetes-all.yaml
  - --image=asia-northeast1-docker.pkg.dev/$PROJECT_ID/app/gke-javaee:$TAG_NAME
  - --location=asia-northeast1
  - --cluster=$CLUSTER_NAME
  - --timeout=30m
  timeout: 1800s
#images: ['asia-northeast1-docker.pkg.dev/$PROJECT_ID/app/gke-javaee:$TAG_NAME']
timeout: 1800s
