apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: spanner-client@noogler-2.iam.gserviceaccount.com
  name: k8s-spanner
#gcloud iam service-accounts add-iam-policy-binding spanner-client@noogler-2.iam.gserviceaccount.com --role roles/iam.workloadIdentityUser --member "serviceAccount:noogler-2.svc.id.goog[default/k8s-spanner]"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaee-front-deploy
  labels:
    app: javaee-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javaee-front
  template:
    metadata:
      labels:
        app: javaee-front
    spec:
      serviceAccountName: k8s-spanner
      containers:
      - name: javaee-front-container
        image: asia-northeast1-docker.pkg.dev/noogler-2/app/gke-javaee:latest
        ports:
        - containerPort: 9080
        env:
        - name: WLP_LOGGING_CONSOLE_FORMAT
          value: JSON
        - name: PROJECT_ID
          value: noogler-2
        - name: PORT
          value: "9080"
        startupProbe:
          httpGet:
            path: /item
            port: 9080
          failureThreshold: 15
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /hostinfo
            port: 9080
        resources:
          requests:
            memory: "500Mi"
            cpu: "250m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaee-back-deploy
  labels:
    app: javaee-back
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javaee-back
  template:
    metadata:
      labels:
        app: javaee-back
    spec:
      serviceAccountName: k8s-spanner
      containers:
      - name: javaee-back-container
        image: asia-northeast1-docker.pkg.dev/noogler-2/app/gke-javaee:latest
        ports:
        - containerPort: 9080
        env:
        - name: WLP_LOGGING_CONSOLE_FORMAT
          value: JSON
        - name: PROJECT_ID
          value: noogler-2
        - name: PORT
          value: "9080"
        startupProbe:
          httpGet:
            path: /item
            port: 9080
          failureThreshold: 15
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /hostinfo
            port: 9080
        resources:
          requests:
            memory: "500Mi"
            cpu: "250m"
