apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-spanner
#gcloud projects add-iam-policy-binding projects/noogler-2 --role=roles/spanner.databaseUser --member=principal://iam.googleapis.com/projects/896536828389/locations/global/workloadIdentityPools/noogler-2.svc.id.goog/subject/ns/default/sa/k8s-spanner --condition=None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaee-front-deploy
  labels:
    app: javaee-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javaee-front
  template:
    metadata:
      labels:
        app: javaee-front
    spec:
      serviceAccountName: k8s-spanner
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      terminationGracePeriodSeconds: 25
      containers:
      - name: javaee-front-container
        image: asia-northeast1-docker.pkg.dev/noogler-2/app/gke-javaee:latest
        ports:
        - containerPort: 9080
        env:
        - name: WLP_LOGGING_CONSOLE_FORMAT
          value: JSON
        - name: PROJECT_ID
          value: noogler-2
        - name: PORT
          value: "9080"
        startupProbe:
          httpGet:
            path: /item
            port: 9080
          failureThreshold: 15
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /hostinfo
            port: 9080
        readinessProbe:
          httpGet:
            path: /item
            port: 9080
        resources:
          requests:
            memory: "320Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "250m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaee-back-deploy
  labels:
    app: javaee-back
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javaee-back
  template:
    metadata:
      labels:
        app: javaee-back
    spec:
      serviceAccountName: k8s-spanner
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      terminationGracePeriodSeconds: 25
      containers:
      - name: javaee-back-container
        image: asia-northeast1-docker.pkg.dev/noogler-2/app/gke-javaee:latest
        ports:
        - containerPort: 9080
        env:
        - name: WLP_LOGGING_CONSOLE_FORMAT
          value: JSON
        - name: PROJECT_ID
          value: noogler-2
        - name: PORT
          value: "9080"
        startupProbe:
          httpGet:
            path: /item
            port: 9080
          failureThreshold: 15
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /hostinfo
            port: 9080
        readinessProbe:
          httpGet:
            path: /item
            port: 9080
        resources:
          requests:
            memory: "320Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: javaee-front-service
spec:
  type: LoadBalancer
  selector:
    app: javaee-front
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: javaee-back-service
spec:
  type: LoadBalancer
  selector:
    app: javaee-back
  ports:
  - name: http-p1
    protocol: TCP
    port: 80
    targetPort: 9080
  - name: http-p2
    protocol: TCP
    port: 9080
    targetPort: 9080
